Meteor.publish("userStatus", function() {
  return Meteor.users.find({ "status.online": true }, { fields: { 'profile':1, 'status':1 } });
});
Meteor.publish('words', function () {
	return Words.find();
});
Meteor.publish('games', function () {
	return Games.find();
});
Meteor.publish('results', function () {
    return Results.find();
});
Meteor.publish('notification', function () {
	return Notification.find();
});

// Users.allow({
// 	insert: function (doc) {
// 		return true;
// 	},
// 	update: function (doc) {
// 		return true;
// 	}
// });

Words.allow({
	insert: function (doc) {
		return true;
	},
	update: function (doc) {
		return true;
	}
});
Games.allow({
	insert: function (doc) {
		return true;
	},
	update: function (doc) {
		return true;
	}
});
Results.allow({
    insert: function (doc) {
        return true;
    },
    update: function (doc) {
        return true;
    }
});
Notification.allow({
	insert: function (doc) {
		return true;
	},
	update: function (doc) {
		return true;
	}
});

Meteor.startup(function () {
	if (!Words.findOne({ english: 'a'})) {
        Words.insert({ english: 'abdomen', korean: '복부|배|' });
        Words.insert({ english: 'about', korean: '…에 대하여|약…|정도|좀|거의|' });
        Words.insert({ english: 'above', korean: '위에|이상인|하늘에|상기(上記)한|' });
        Words.insert({ english: 'abroad', korean: '해외에|외국에|널리|' });
        Words.insert({ english: 'absolutely', korean: '절대적으로|전혀|완전히|물론|정말로|' });
        Words.insert({ english: 'academy', korean: '아카데미|학교|학술원|학원|교육기관|' });
        Words.insert({ english: 'accomplishment', korean: '성취|업적|완성|' });
        Words.insert({ english: 'accumulation', korean: '축적|누적|축적물|' });
        Words.insert({ english: 'accurately', korean: '정확하게|그대로|' });
        Words.insert({ english: 'acquire', korean: '얻다|인수하다|갖다|배우다|구입하다|' });
        Words.insert({ english: 'across', korean: '… 전역에서|가로질러서|건너다|걸쳐서|지름으로|' });
        Words.insert({ english: 'active', korean: '활동적인|적극적인|활발한|현역의|능동적인|' });
        Words.insert({ english: 'adapt', korean: '…을 적응시키다|순응하다|개작하다|' });
        Words.insert({ english: 'addition', korean: '추가|덧셈|증축|등재|' });
        Words.insert({ english: 'address', korean: '주소|연설하다|이야기하다|부르다|' });
        Words.insert({ english: 'adhere', korean: '고수하다|들러붙다|달라붙다|' });
        Words.insert({ english: 'adjourn', korean: '휴회하다|회의를 연기하다|' });
        Words.insert({ english: 'adjust', korean: '조정되다|적응하다|감안하다|조절하다|맞추다|' });
        Words.insert({ english: 'admission', korean: '입학|입장|인정|입원|입국|' });
        Words.insert({ english: 'advantage', korean: '이점|유리|이익|우위|혜택|' });
        Words.insert({ english: 'advantageous', korean: '유리한|…하기 좋은|이로운|' });
        Words.insert({ english: 'advent', korean: '출현|도래|그리스도의 강림|' });
        Words.insert({ english: 'adversity', korean: '역경|재난|불운|' });
        Words.insert({ english: 'advertiser', korean: '광고자|광고인|광고주|' });
        Words.insert({ english: 'advisable', korean: '타당한|현명한|권할 만한|' });
        Words.insert({ english: 'advise', korean: '조언하다|권하다|알리다|…하는 게 좋다|상담하다|' });
        Words.insert({ english: 'affect', korean: '영향을 주다|작용하다|감염시키다|…체하다|' });
        Words.insert({ english: 'after school', korean: '방과 후의|방과 후|' });
        Words.insert({ english: 'afternoon', korean: '오후|점심|' });
        Words.insert({ english: 'again', korean: '다시|또|다시 한 번|' });
        Words.insert({ english: 'age', korean: '나이|시대|오래되다|노인들|오랫동안|' });
        Words.insert({ english: 'ageless', korean: '영원한|언제나 젊은|불로의|' });
        Words.insert({ english: 'agenda', korean: '의사 일정|의제|비망록|' });
        Words.insert({ english: 'agreeable', korean: '동의할 만한|마음에 드는|쾌적한|상냥한|' });
        Words.insert({ english: 'agreement', korean: '합의|협정|계약|동의|조화|' });
        Words.insert({ english: 'agriculture', korean: '농업|축산|' });
        Words.insert({ english: 'aide', korean: '측근|보좌관|참모|조력자|부관|' });
        Words.insert({ english: 'aim', korean: '목표|목적|겨냥하다|노리다|조준하다|' });
        Words.insert({ english: 'alert', korean: '경계|주의하다|집중하다|알림|기민한|' });
        Words.insert({ english: 'alive', korean: '살아 있는|생기에 넘치는|이 세상의|계속하여|생생한|' });
        Words.insert({ english: 'all', korean: '모든|모두|다|전부|전혀|' });
        Words.insert({ english: 'all around', korean: '다재다능한|전반에 걸친|전면적인|' });
        Words.insert({ english: 'all at on-ce', korean: '갑자기, 다 한꺼번에|' });
        Words.insert({ english: 'all day', korean: '종일의, 하루 종일 걸리는|' });
        Words.insert({ english: 'along', korean: '함께|…을 따라|동안에|가지고|계속|' });
        Words.insert({ english: 'already', korean: '이미|벌써|충분히|이전에|지금까지|' });
        Words.insert({ english: 'amazing', korean: '놀라운|멋진|대단한|흥미로운|' });
        Words.insert({ english: 'ambulance', korean: '구급차|앰뷸런스|' });
        Words.insert({ english: 'America', korean: '미국|아메리카|' });
        Words.insert({ english: 'amnesty', korean: '대사|특사|…에게 대사를 내리다|' });
        Words.insert({ english: 'among', korean: '…중에|…사이에|대한|상호간에|가운데|' });
        Words.insert({ english: 'anxiety', korean: '불안|걱정|염려|근심|긴장|' });
        Words.insert({ english: 'any', korean: '어떤|전혀|아무|어느|누군가|' });
        Words.insert({ english: 'anything', korean: '무엇이든|아무것도|어느 것이든|조금이라도|' });
        Words.insert({ english: 'anyway', korean: '어쨌든|어차피|아무튼|결국|그런데|' });
        Words.insert({ english: 'appetizer', korean: '식욕을 돋우는 것|전채|식욕 촉진제|' });
        Words.insert({ english: 'apply', korean: '적용하다|지원하다|신청하다|바르다|해당되다|' });
        Words.insert({ english: 'appoint', korean: '임명하다|지명하다|지정하다|' });
        Words.insert({ english: 'appreciate', korean: '감사하다|인정하다|감상하다|평가|이해하다|' });
        Words.insert({ english: 'approach', korean: '접근법|접근하다|방법|다가오다|육박하다|' });
        Words.insert({ english: 'archipelago', korean: '다도해|군도|에게 해|' });
        Words.insert({ english: 'argument', korean: '주장|논쟁|말다툼|논점|논거|' });
        Words.insert({ english: 'around', korean: '주변에|주위에|돌아다니는|근처에|' });
        Words.insert({ english: 'arrive', korean: '도착하다|오다|일어나다|성공하다|' });
        Words.insert({ english: 'artist', korean: '예술가|화가|아티스트|가수|미술가|' });
        Words.insert({ english: 'as usual', korean: '언제나 처럼|여느 때처럼|' });
        Words.insert({ english: 'ask', korean: '묻다|요청하다|질문하다|부탁하다|말씀하다|' });
        Words.insert({ english: 'aspirin', korean: '아스피린|그 정제|진통제|' });
        Words.insert({ english: 'attendee', korean: '참석자|출석자|' });
        Words.insert({ english: 'attention', korean: '관심|주의력|주목|주의|집중|' });
        Words.insert({ english: 'attentive', korean: '주의 깊은|세심한|친절한|' });
        Words.insert({ english: 'attorney', korean: '변호사| 지방 검사|법무장관|법정대리인| 위임장|' });
        Words.insert({ english: 'attractive', korean: '매력적인|매혹적인|' });
        Words.insert({ english: 'auction', korean: '경매|…을 경매하다|…을 경매에 부치다|' });
        Words.insert({ english: 'audit', korean: '회계 감사|감사하다|청강하다|' });
        Words.insert({ english: 'authentic', korean: '진짜의|진정한|실제의|믿을 만한|' });
        Words.insert({ english: 'authority', korean: '당국|권한|권위|권위자|권력|' });
        Words.insert({ english: 'authorization', korean: '위임|허가|권한 부여|' });
        Words.insert({ english: 'authorship', korean: '저작업|원작자임|출처|' });
        Words.insert({ english: 'automate', korean: '자동화하다|오토메이션화하다|오토메이션 기술을 사용하다|' });
        Words.insert({ english: 'available', korean: '가능한|이용할 수 있는|유용한|시간이 있는|유효한|' });
        Words.insert({ english: 'avalanche', korean: '쇄도하다|사태|눈사태|' });
        Words.insert({ english: 'backyard', korean: '뒤뜰|세력 범위|' });
        Words.insert({ english: 'bad', korean: '나쁜|좋지 않은|심한|잘못된|상한|' });
        Words.insert({ english: 'bag', korean: '가방|봉지|백|주머니|봉투|' });
        Words.insert({ english: 'bake', korean: '굽다|' });
        Words.insert({ english: 'balance', korean: '균형|잔고|안정|조화|' });
        Words.insert({ english: 'ban', korean: '금지|금지령|반대|금하다|비난|' });
        Words.insert({ english: 'bang', korean: '굉음|두드리다|앞머리|훌륭히|속이 후련한|' });
        Words.insert({ english: 'bankruptcy', korean: '파산|부도|' });
        Words.insert({ english: 'banner', korean: '현수막|배너|기치|대표|' });
        Words.insert({ english: 'bar', korean: '바|술집|막대|판매대|' });
        Words.insert({ english: 'barely', korean: '거의 …않다|간신히|겨우|' });
        Words.insert({ english: 'baseball', korean: '야구|베이스볼|' });
        Words.insert({ english: 'based on', korean: '…을 바탕으로,…을 근거하여|' });
        Words.insert({ english: 'basketball', korean: '농구|농구공|' });
        Words.insert({ english: 'bat', korean: '박쥐|배트|방망이|치다|타석|' });
        Words.insert({ english: 'bath', korean: '목욕|목욕물|욕조|욕실|' });
        Words.insert({ english: 'batter', korean: '타자|공격하다|반죽|' });
        Words.insert({ english: 'beautiful', korean: '아름다운|멋있는|예쁜|훌륭한|화창한|' });
        Words.insert({ english: 'beauty', korean: '아름다움|미인|미|미용의|미녀|' });
        Words.insert({ english: 'beginner', korean: '초보자|초심자|' });
        Words.insert({ english: 'beginning', korean: '시작|초|처음|기원|개시|' });
        Words.insert({ english: 'belong', korean: '속하다|…의 것이다|소유하다|어울리다|' });
        Words.insert({ english: 'below', korean: '아래에|…이하의|영하의|' });
        Words.insert({ english: 'beneath', korean: '아래에|밑에|지하에|가치가 없는|…의 이면에|' });
        Words.insert({ english: 'benefit', korean: '이익|혜택|도움이 되다|' });
        Words.insert({ english: 'best', korean: '최고의|가장 …한|최선의|베스트|최대의|' });
        Words.insert({ english: 'big', korean: '큰|중요한|많이|대단한|' });
        Words.insert({ english: 'bike', korean: '자전거|오토바이|' });
        Words.insert({ english: 'bill', korean: '법안|빌|지폐|청구서|계산서|' });
        Words.insert({ english: 'billion', korean: '10억|막대한 수|' });
        Words.insert({ english: 'biologist', korean: '생물학자|' });
        Words.insert({ english: 'birth', korean: '탄생|태어남|출생|출산|낳다|' });
        Words.insert({ english: 'bit', korean: '조금|약간|' });
        Words.insert({ english: 'blow on-e’s nose', korean: '코를 풀다 |' });
        Words.insert({ english: 'board', korean: '위원회|이사회|…판|탑승하다|보드|' });
        Words.insert({ english: 'boat', korean: '배|보트|' });
        Words.insert({ english: 'bone', korean: '뼈|골격|유골|' });
        Words.insert({ english: 'bored', korean: '지루한|싫증난|' });
        Words.insert({ english: 'borrow', korean: '빌리다|대여하다|차용하다|빚지다|' });
        Words.insert({ english: 'botch', korean: '…을 망쳐 놓다|종기|엉성한 일|' });
        Words.insert({ english: 'bother', korean: '성가시게 하다|괴롭히다|신경쓰이다|귀찮게 하다|걱정하다|' });
        Words.insert({ english: 'bottle', korean: '병|우유|병에 담다|술|술병|' });
        Words.insert({ english: 'bottom', korean: '바닥|하위|아래|밑바닥|최하의|' });
        Words.insert({ english: 'bought', korean: '샀다|구입했다|장만했다|' });
        Words.insert({ english: 'boyfriend', korean: '남자 친구|애인|보이프렌드|' });
        Words.insert({ english: 'brain', korean: '뇌|두뇌|머리|브레인|' });
        Words.insert({ english: 'break out', korean: '발생하다|일어나다|탈옥하다|벗어나다|탈출하다|' });
        Words.insert({ english: 'bridge', korean: '다리|교량|브리지|메우다|육교|' });
        Words.insert({ english: 'cabbage', korean: '양배추|' });
        Words.insert({ english: 'cabin', korean: '객실|오두막|' });
        Words.insert({ english: 'cafeteria', korean: '구내 식당|카페테리아|' });
        Words.insert({ english: 'call', korean: '부르다|전화하다|요구하다|말하다|연락하다|' });
        Words.insert({ english: 'called', korean: '[서술형용사] [이름이] …라고 불리는|' });
        Words.insert({ english: 'camera-shy', korean: '사진 찍히기 싫어하는  |' });
        Words.insert({ english: 'can', korean: '할 수 있다|캔|통조림|' });
        Words.insert({ english: 'candidate', korean: '후보자|지원자|수험생|' });
        Words.insert({ english: 'capable', korean: '능력있는|가능성있는|가능한|할 수 있는|유능한|' });
        Words.insert({ english: 'capital', korean: '수도|자본|자금|자산|대문자|' });
        Words.insert({ english: 'capitalize on', korean: '~을 이용하다, 틈타다.|' });
        Words.insert({ english: 'captive', korean: '감금된|포로|어쩔 수 없는|' });
        Words.insert({ english: 'capture', korean: '포획하다|사로잡다|…을 붙잡다|' });
        Words.insert({ english: 'care for', korean: 'have a liking, fondness, or taste|' });
        Words.insert({ english: 'carry', korean: '휴대하다|수행하다|싣다|옮기다|갖다|' });
        Words.insert({ english: 'carry out', korean: '성취하다|수행하다|이행하다|' });
        Words.insert({ english: 'cart', korean: '카트|수레|마차|' });
        Words.insert({ english: 'case', korean: '경우|사건|소송|상황|상자|' });
        Words.insert({ english: 'cash', korean: '현금|돈|현찰|현금화하다|' });
        Words.insert({ english: 'casual', korean: '캐주얼의|편한|평상복의|평상시의|우연한|' });
        Words.insert({ english: 'century', korean: '세기|100년|' });
        Words.insert({ english: 'cereal', korean: '시리얼|곡물|' });
        Words.insert({ english: 'certainly', korean: '분명히|물론이지|확실히|정말로|반드시|' });
        Words.insert({ english: 'chairperson', korean: '사회자|회장|의장|' });
        Words.insert({ english: 'challenge', korean: '도전|문제|난제|이의를 제기하다|자극하다|' });
        Words.insert({ english: 'cheat', korean: '속이다|부정 행위|바람 피우다|커닝|사기꾼|' });
        Words.insert({ english: 'check', korean: '확인하다|수표|점검하다|견제|검사|' });
        Words.insert({ english: 'Chinese', korean: '중국인|중국의|중국어|중국 사람|' });
        Words.insert({ english: 'choice', korean: '선택|결정|선정|종류|' });
        Words.insert({ english: 'choir', korean: '합창하다|성가대|' });
        Words.insert({ english: 'choral', korean: '합창의|합창으로 부르는|' });
        Words.insert({ english: 'chorus', korean: '합창|코러스|이구동성|' });
        Words.insert({ english: 'cigarette', korean: '담배|궐련|' });
        Words.insert({ english: 'circle', korean: '원|서클|돌다|사회|그룹|' });
        Words.insert({ english: 'citizenship', korean: '시민권|시민의 신분|국적|' });
        Words.insert({ english: 'clay', korean: '진흙|클레이|점토|' });
        Words.insert({ english: 'clean', korean: '깨끗한|청소하다|맑은|치우다|지우다|' });
        Words.insert({ english: 'clean up', korean: '마무리하다|떼돈을 벌다|옷차림을 말쑥하게 하다|' });
        Words.insert({ english: 'clerk', korean: '점원|직원|판매원|사무원|서기|' });
        Words.insert({ english: 'climax', korean: '절정|최고점|클라이맥스|극상|' });
        Words.insert({ english: 'clip', korean: '동영상|클립|속도|탄창|자르다|' });
        Words.insert({ english: 'closely', korean: '긴밀히|면밀하게|유심히|가까이|깊은|' });
        Words.insert({ english: 'clothes', korean: '옷|세탁물|의복|의상|옷가지|' });
        Words.insert({ english: 'club', korean: '클럽|팀|동아리|구단|골프채|' });
        Words.insert({ english: 'coast', korean: '해안|연안|해변|' });
        Words.insert({ english: 'coat', korean: '코트|칠하다|외피|외투|도금|' });
        Words.insert({ english: 'coke', korean: '코크스|' });
        Words.insert({ english: 'colleague', korean: '동료|' });
        Words.insert({ english: 'college', korean: '대학|연구소|칼리지|' });
        Words.insert({ english: 'color', korean: '색|색깔|색상|컬러|색채|' });
        Words.insert({ english: 'consequence', korean: '결과|중요성|결말|' });
        Words.insert({ english: 'consider', korean: '고려하다|여기다|생각한다|간주하다|검토하다|' });
        Words.insert({ english: 'considerable', korean: '상당한|꽤|' });
        Words.insert({ english: 'consist of', korean: '…으로 구성되다. |' });
        Words.insert({ english: 'consumption', korean: '소비량|소비|폐결핵|' });
        Words.insert({ english: 'contact', korean: '연락|접촉|콘택트 렌즈|시선을 마주치다|교제|' });
        Words.insert({ english: 'contain', korean: '들어있다|포함하다|담다|함유하다|담고 있다|' });
        Words.insert({ english: 'content', korean: '내용|콘텐츠|만족하는|함유량|목차|' });
        Words.insert({ english: 'contentment', korean: '만족|흡족해함|' });
        Words.insert({ english: 'contest', korean: '대회|콘테스트|경쟁하다|선거|' });
        Words.insert({ english: 'convergence', korean: '집중성|한점에의 집합|집합함|' });
        Words.insert({ english: 'conversion', korean: '전환|환산|융합|변화|' });
        Words.insert({ english: 'convert', korean: '전환하다|바꾸다|개종하다|개조하다|득점하다|' });
        Words.insert({ english: 'convey', korean: '전달하다|전하다|나타내다|의미하다|' });
        Words.insert({ english: 'convince', korean: '설득하다|확신시키다|납득시키다|' });
        Words.insert({ english: 'convoy', korean: '호송하다|호위대|호위함|' });
        Words.insert({ english: 'cook', korean: '요리사|요리하다|만들다|쿡|조리된|' });
        Words.insert({ english: 'cool', korean: '멋진|시원한|식히다|좋다|침착한|' });
        Words.insert({ english: 'cooperate', korean: '협력하다|협조하다|협동하다|' });
        Words.insert({ english: 'coral', korean: '산호|' });
        Words.insert({ english: 'core', korean: '핵심|중요한|코어|근원|핵|' });
        Words.insert({ english: 'corner', korean: '모퉁이|구석|코너|궁지|' });
        Words.insert({ english: 'corruption', korean: '부패|비리|부정|타락|' });
        Words.insert({ english: 'cram', korean: '밀어 넣다|' });
        Words.insert({ english: 'crash', korean: '충돌하다|추락하다|고장나다|붕괴하다|폭락|' });
        Words.insert({ english: 'custom', korean: '세관|관습|문화|풍습|맞춤의|' });
        Words.insert({ english: 'dad', korean: '아빠|' });
        Words.insert({ english: 'daily', korean: '매일의|일상적인|데일리|날마다|' });
        Words.insert({ english: 'damage', korean: '피해|손상|손해|배상금|해치다|' });
        Words.insert({ english: 'dangerous', korean: '위험한|' });
        Words.insert({ english: 'dark', korean: '어두운|지다|검은|다크|모르다|' });
        Words.insert({ english: 'data', korean: '자료|데이터|정보|' });
        Words.insert({ english: 'dating', korean: '날짜 기입|선일부|연대 결정|' });
        Words.insert({ english: 'daughter', korean: '딸|여성|양녀|파생|' });
        Words.insert({ english: 'dead', korean: '죽은|사망|시신|다 되다|돌아가신|' });
        Words.insert({ english: 'deal', korean: '거래|다루다|계약|대처하다|처리|' });
        Words.insert({ english: 'declare', korean: '선언하다|말하다|선고하다|주장|신고하다|' });
        Words.insert({ english: 'deep', korean: '깊은|심|매우|많다|딥|' });
        Words.insert({ english: 'defect', korean: '결함|탈주|장애|이탈|' });
        Words.insert({ english: 'delay', korean: '지연시키다|연기하다|늦추다|미루다|지체시키다|' });
        Words.insert({ english: 'delicious', korean: '맛있는|맛좋은|매우 맛있는|즐거운|아름다운|' });
        Words.insert({ english: 'delivery', korean: '배달|배송|인도|운송|납품|' });
        Words.insert({ english: 'dentist', korean: '치과의사|' });
        Words.insert({ english: 'depend', korean: '따라|달리다|의존하다|의지하다|좌우되다|' });
        Words.insert({ english: 'describe', korean: '묘사하다|설명하다|표현하다|기술하다|그리다|' });
        Words.insert({ english: 'disappointing', korean: '실망시키는|기대보다 못한|기대에 어긋나는|' });
        Words.insert({ english: 'discuss', korean: '논의하다|토론하다|상담하다|언급|논란|' });
        Words.insert({ english: 'disguise', korean: '위장|가장하다|숨기다|' });
        Words.insert({ english: 'display', korean: '(작품을) 전시하다|보여주다|디스플레이|표현하다|진열하다|' });
        Words.insert({ english: 'distinction', korean: '구별|차이|차별|영예|' });
        Words.insert({ english: 'distract', korean: '주의를 빼앗다|관심이 멀어지다|산만하게 하다|초점을 흐리다|' });
        Words.insert({ english: 'distribute', korean: '배포하다|공급하다|나눠주다|분배하다|기부하다|' });
        Words.insert({ english: 'diverse', korean: '다양한|여러 가지의|광범위한|다른|각계 각층의|' });
        Words.insert({ english: 'downsize', korean: '축소하다|소형화하다|줄이다|' });
        Words.insert({ english: 'dragonfly', korean: '잠자리|' });
        Words.insert({ english: 'drain', korean: '배수하다|소비하다|유출하다|허사가 되다|마시다|' });
        Words.insert({ english: 'due', korean: '예정인|정당한|때문에|세금|인해|' });
        Words.insert({ english: 'dugong', korean: '듀공|' });
        Words.insert({ english: 'during', korean: '…동안|…중에도|…사이에|' });
        Words.insert({ english: 'each other', korean: '서로|상호|' });
        Words.insert({ english: 'eagle', korean: '한화 이글스 프로야구단|독수리|이글|' });
        Words.insert({ english: 'early', korean: '초|일찍|초기|이른|어린|' });
        Words.insert({ english: 'earning', korean: '얻다|소득|벌다|' });
        Words.insert({ english: 'ease', korean: '완화하다|덜어주다|편해지다|쉬움|느슨해지다|' });
        Words.insert({ english: 'economic', korean: '경제의|경기의|' });
        Words.insert({ english: 'economy', korean: '경제|경기|이코노미|' });
        Words.insert({ english: 'education', korean: '교육|훈련|교양|' });
        Words.insert({ english: 'effort', korean: '노력|작업|활동|' });
        Words.insert({ english: 'eggplant', korean: '가지|가지 열매|진한 보라색|' });
        Words.insert({ english: 'either', korean: '또한|어느 쪽|역시|양쪽의|게다가|' });
        Words.insert({ english: 'elbow', korean: '팔꿈치|팔|엘보우|팔꿈치로 밀어젖히며 나아가다|' });
        Words.insert({ english: 'elder', korean: '어른|노인|연장자|장로|고참|' });
        Words.insert({ english: 'election', korean: '선거|투표|당선|선정|선택|' });
        Words.insert({ english: 'elegant', korean: '우아한|훌륭한|' });
        Words.insert({ english: 'elevator', korean: '엘리베이터|' });
        Words.insert({ english: 'else', korean: '다른|더|그 밖에|아니면|' });
        Words.insert({ english: 'emergency', korean: '비상|긴급한|응급|위기|급변|' });
        Words.insert({ english: 'emotional', korean: '감정적인|감정의|감정에 호소하는|' });
        Words.insert({ english: 'empty', korean: '빈|비우다|없어지다|없는|공허한|' });
        Words.insert({ english: 'enclose', korean: '동봉하다|첨부하다|에워싸다|둘러싸다|' });
        Words.insert({ english: 'envelope', korean: '봉투|' });
        Words.insert({ english: 'envious', korean: '시기하는|부러워하는|' });
        Words.insert({ english: 'envy', korean: '부러워하다|질투하다|선망|' });
        Words.insert({ english: 'errand', korean: '심부름|볼일|' });
        Words.insert({ english: 'error', korean: '실수|오류|잘못|오차|에러|' });
        Words.insert({ english: 'eternal', korean: '영원한|불멸의|무한한|불변의|천추의|' });
        Words.insert({ english: 'even', korean: '평평해지다|균등해지다|백중해지다|같은|' });
        Words.insert({ english: 'ever', korean: '지금까지|이전에|항상|결코|언제까지나|' });
        Words.insert({ english: 'everlasting', korean: '영원한|끊임없는|끝없는|' });
        Words.insert({ english: 'everything', korean: '모든|모든 것|모두|만사|최선|' });
        Words.insert({ english: 'evil', korean: '사악한|악|악마|나쁜|해악|' });
        Words.insert({ english: 'exactly', korean: '정확히|바로|그렇소|확실히|꼭|' });
        Words.insert({ english: 'exam', korean: '시험|조사|' });
        Words.insert({ english: 'excellent', korean: '훌륭한|뛰어난|좋다|수의|우수한|' });
        Words.insert({ english: 'excited', korean: '흥분한|신이 난|들뜨다|기대하는|열광하는|' });
        Words.insert({ english: 'exciting', korean: '흥미진진한|신나는|재미있는|흥분시키는|설레는|' });
        Words.insert({ english: 'excuse me', korean: '실례합니다|저기요|죄송합니다|잠깐만요|여보세요|' });
        Words.insert({ english: 'existence', korean: '존재|현존|생존|생활|실체|' });
        Words.insert({ english: 'exit', korean: '출구|나가다|퇴출되다|종료하다|' });
        Words.insert({ english: 'face', korean: '얼굴|직면하다|표정|' });
        Words.insert({ english: 'factory', korean: '공장|회사|제조소|팩토리|' });
        Words.insert({ english: 'fair', korean: '공정한|공평한|박람회|전시회|타당한|' });
        Words.insert({ english: 'familiar', korean: '익숙한|친숙한|잘 아는|낯익은|' });
        Words.insert({ english: 'familiar with', korean: '…을 잘 알고 있는|' });
        Words.insert({ english: 'family', korean: '가족|가문|식구|' });
        Words.insert({ english: 'fan', korean: '팬|좋아하는|선풍기|부채|흩어지다|' });
        Words.insert({ english: 'fantastic', korean: '환상적인|멋진|이유없는|상상의|이상한|' });
        Words.insert({ english: 'fare', korean: '운임|요금|실적을 내다|상연물|' });
        Words.insert({ english: 'fashionable', korean: '멋있는|패션 감각이 있는|유행의|' });
        Words.insert({ english: 'fast food', korean: '패스트푸드|즉석 식품|즉석 요리의|' });
        Words.insert({ english: 'fat', korean: '지방|뚱뚱한|살찐|비만한|기름|' });
        Words.insert({ english: 'fat­-free milk', korean: '무지방 우유|' });
        Words.insert({ english: 'fault', korean: '잘못|결점|탓|흠|실수|' });
        Words.insert({ english: 'favorite', korean: '좋아하는|마음에 드는|인기 있는|우승 후보|' });
        Words.insert({ english: 'feather', korean: '깃털|가벼운 것|' });
        Words.insert({ english: 'find', korean: '찾다|발견하다|알다|알아보다|' });
        Words.insert({ english: 'fine', korean: '좋은|벌금|잘|미세한|고급의|' });
        Words.insert({ english: 'fire', korean: '불|해고하다|발사하다|화재|소방의|' });
        Words.insert({ english: 'firefly', korean: '반딧불이|개똥벌레|반딧불|' });
        Words.insert({ english: 'firmly', korean: '확고하게|강하게|꽉|자신 있게|' });
        Words.insert({ english: 'flow', korean: '흐르다|흐름|유입|유동|유출|' });
        Words.insert({ english: 'flowerpot', korean: '화분|' });
        Words.insert({ english: 'follow', korean: '따르다|뒤를 잇다|따라가다|지켜보다|지키다|' });
        Words.insert({ english: 'food', korean: '음식|식품|식량|먹이|푸드|' });
        Words.insert({ english: 'football', korean: '축구|미식 축구|풋볼|' });
        Words.insert({ english: 'footwork', korean: '풋워크|발놀림|교묘한 처리|' });
        Words.insert({ english: 'for', korean: '…을 위하여|…을 기념하여|…용의|' });
        Words.insert({ english: 'for a minute', korean: '잠시, 잠깐|' });
        Words.insert({ english: 'for a moment', korean: '잠깐 동안|당장 그때만|잠시 동안|' });
        Words.insert({ english: 'for a while', korean: '잠깐, 잠시 동안 |' });
        Words.insert({ english: 'for example', korean: '예를 들면|가령|예컨대|한 예|' });
        Words.insert({ english: 'forbid', korean: '금지하다|어렵게하다|용납하지 않다|' });
        Words.insert({ english: 'forecast', korean: '전망하다|예상|예보|내다보다|' });
        Words.insert({ english: 'formula', korean: '공식|포뮬러 1|방식|유동식|처방|' });
        Words.insert({ english: 'forth', korean: '앞으로|밖으로|이후|' });
        Words.insert({ english: 'forum', korean: '공개 토론|토론회|좌담회|' });
        Words.insert({ english: 'forward', korean: '앞으로|발전한|포워드|전진하는|진보적인|' });
        Words.insert({ english: 'free', korean: '무료의|자유의|…이 없는|해방시키다|벗어난|' });
        Words.insert({ english: 'freedom', korean: '자유|석방|' });
        Words.insert({ english: 'freely', korean: '아낌없이|자유롭게|기꺼이|' });
        Words.insert({ english: 'freeze', korean: '얼다|동결|냉동하다|추워지다|멈추다|' });
        Words.insert({ english: 'frequent', korean: '자주|잦은|빈번한|종종|흔한|' });
        Words.insert({ english: 'friction', korean: '마찰|불화|' });
        Words.insert({ english: 'fried', korean: '튀긴|프라이|취한|' });
        Words.insert({ english: 'frugal', korean: '검소한|절약하는|간소한|' });
        Words.insert({ english: 'fry', korean: '튀기다|감자튀김|프라이|튀김|망가지다|' });
        Words.insert({ english: 'fun', korean: '재미있는|즐거운|놀리다|신나는|장난|' });
        Words.insert({ english: 'funding', korean: '재원|재정적 지출|자금 제공|' });
        Words.insert({ english: 'girlfriend', korean: '여자 친구|애인|연인|' });
        Words.insert({ english: 'glad', korean: '기쁜|좋은|다행인|고마운|반가운|' });
        Words.insert({ english: 'glove', korean: '장갑|글러브|' });
        Words.insert({ english: 'go well', korean: '잘 가, 안녕히 가세요. [작별의 말]|' });
        Words.insert({ english: 'golden', korean: '황금의|골든|가장 좋은|절호의|' });
        Words.insert({ english: 'golf', korean: '골프|' });
        Words.insert({ english: 'good', korean: '좋은|잘|훌륭한|즐거운|착한|' });
        Words.insert({ english: 'good morning', korean: '안녕하십니까|좋은 아침입니다|' });
        Words.insert({ english: 'green pepper', korean: '피망|양고추|' });
        Words.insert({ english: 'greenfly', korean: '자주진딧물|열광적인 야구팬|진딧물|' });
        Words.insert({ english: 'has', korean: 'have의 3인칭·단수·직설법·현재형|' });
        Words.insert({ english: 'have', korean: '가지다|얻다|걸리다|소유하다| 낳다|' });
        Words.insert({ english: 'heavy', korean: '무거운|강력한|중(重)…|과중한|심한|' });
        Words.insert({ english: 'helmet', korean: '헬멧|안전모|마스크|투구|머리 모양|' });
        Words.insert({ english: 'help', korean: '도움|돕다|도와주다|기여하다|' });
        Words.insert({ english: 'her', korean: '그녀의|그녀를|그녀가|여자|그녀에게|' });
        Words.insert({ english: 'here', korean: '여기|이곳|이쪽|저기|' });
        Words.insert({ english: 'hidden', korean: '숨은|감춰진|비밀의|남모르게|' });
        Words.insert({ english: 'hire', korean: '고용하다|채용하다|뽑다|사람을 쓰다|빌리다|' });
        Words.insert({ english: 'his', korean: '그의|그 사람의|그의 것|신의|' });
        Words.insert({ english: 'hit', korean: '치다|히트를 치다|타격|달하다|명중하다|' });
        Words.insert({ english: 'hobby', korean: '취미|' });
        Words.insert({ english: 'hold', korean: '열다|보유하다|잡다|기다리다|' });
        Words.insert({ english: 'hold out', korean: '견디다|지탱되다|유지되다|' });
        Words.insert({ english: 'homeroom', korean: '홈룸|홈룸 시간|' });
        Words.insert({ english: 'honest', korean: '정직한|솔직한|성실한|정당한|' });
        Words.insert({ english: 'honesty', korean: '정직|솔직|양심|청렴결백|' });
        Words.insert({ english: 'honor', korean: '명예|경의|영광|수여하다|상|' });
        Words.insert({ english: 'How are you?', korean: '안녕하십니까?|' });
        Words.insert({ english: 'if', korean: '만약|…라면|만일|' });
        Words.insert({ english: 'illegal', korean: '불법적인|법으로 금지된|위법인|' });
        Words.insert({ english: 'illiterate', korean: '문맹|' });
        Words.insert({ english: 'illustrate', korean: '설명하다|삽화를 넣다|예시하다|' });
        Words.insert({ english: 'immediate', korean: '즉각적인|당장|즉시|시급한|직접적인|' });
        Words.insert({ english: 'immigration', korean: '이민|출입국 관리|이주|' });
        Words.insert({ english: 'import', korean: '수입하다|들여오다|중요하다|' });
        Words.insert({ english: 'important', korean: '중요한|주요한|중대한|소중한|' });
        Words.insert({ english: 'impress', korean: '인상|감동시키다|감명을 주다|' });
        Words.insert({ english: 'impression', korean: '인상|생각|흉내|' });
        Words.insert({ english: 'in', korean: '…안에|…으로|…에|' });
        Words.insert({ english: 'in a hurry', korean: '서둘러|황급히|조급히|' });
        Words.insert({ english: 'in case of', korean: '…의 경우에는|…한 때에는|…에 대비하여|' });
        Words.insert({ english: 'in deep thought', korean: '[깊은] 생각에 잠겨. |' });
        Words.insert({ english: 'in fact', korean: '사실상, 사실은,사실에 있어서|' });
        Words.insert({ english: 'in front of', korean: '앞에|앞길에|눈앞에서|앞쪽|' });
        Words.insert({ english: 'in person', korean: '직접의|실제로 하는|개인적으로|실물은|본인이 직접|' });
        Words.insert({ english: 'in public', korean: '공공|공|대중|공개적으로|국민|' });
        Words.insert({ english: 'in short', korean: '요컨대|간단히 말해|요약하면|' });
        Words.insert({ english: 'in the hospital', korean: '영 입원[퇴원]하여|' });
        Words.insert({ english: 'include', korean: '포함하다|포괄하다|함유하다|' });
        Words.insert({ english: 'ink', korean: '잉크|서명하다|먹물|' });
        Words.insert({ english: 'instead', korean: '대신에|보다|하지만|그렇기는커녕|아닌|' });
        Words.insert({ english: 'institute', korean: '연구소|전문교육기관|대학교|협회|시행하다|' });
        Words.insert({ english: 'instruction', korean: '지시|설명|교육|교본|방법|' });
        Words.insert({ english: 'insurance', korean: '보험|보험금|' });
        Words.insert({ english: 'intelligence', korean: '정보|지능|첩보|지성|지적|' });
        Words.insert({ english: 'interest', korean: '이자|관심|이해관계|' });
        Words.insert({ english: 'interesting', korean: '흥미로운|재미있는|놀라운|' });
        Words.insert({ english: 'international', korean: '국제적인|인터내셔널|국제의|국제간의|' });
        Words.insert({ english: 'international marriage', korean: '국제 결혼|' });
        Words.insert({ english: 'interview', korean: '인터뷰|면접|면담|회견|' });
        Words.insert({ english: 'invade', korean: '침략하다|침입하다|침해하다|' });
        Words.insert({ english: 'investigate', korean: '조사하다|수사하다|살피다|' });
        Words.insert({ english: 'invitation', korean: '초대|초청|' });
        Words.insert({ english: 'irregular', korean: '비정규의|불규칙의|비정상적인|불안정|' });
        Words.insert({ english: 'island', korean: '섬|도|아일랜드|' });
        Words.insert({ english: 'issue', korean: '문제|이슈|사안|발행하다|쟁점|' });
        Words.insert({ english: 'It’s up to you', korean: '당신에게 달려 있습니다. |' });
        Words.insert({ english: 'japan', korean: '일본|' });
        Words.insert({ english: 'job', korean: '일|직업|일자리|직무|수술|' });
        Words.insert({ english: 'joke', korean: '농담|장난|놀리다|재담|' });
        Words.insert({ english: 'journalist', korean: '기자|언론인|저널리스트|' });
        Words.insert({ english: 'judge', korean: '판사|판단하다|판결하다|심판하다|평가하다|' });
        Words.insert({ english: 'junior', korean: '주니어|1학년인|3학년인|2학년인|후배|' });
        Words.insert({ english: 'just', korean: '것만 |그냥|방금|단지|그저|' });
        Words.insert({ english: 'just a little', korean: '살짝, 조금만|' });
        Words.insert({ english: 'justice', korean: '정의|재판|사법|판사|공정|' });
        Words.insert({ english: 'juvenile', korean: '청소년의|아이다운|유치한|' });
        Words.insert({ english: 'knowledge', korean: '지식|아는 것|학식|인지|' });
        Words.insert({ english: 'lack', korean: '부족|…이 없다|결핍|부재|모자라다|' });
        Words.insert({ english: 'lake', korean: '호수|연못|' });
        Words.insert({ english: 'law maker', korean: '국회의원|' });
        Words.insert({ english: 'lax', korean: '느슨한|태만한|로스엔젤레스 공항|' });
        Words.insert({ english: 'leadership', korean: '지도력|리더십|대표|선도|권력|' });
        Words.insert({ english: 'leaf', korean: '나뭇잎|잎|리프|잎사귀|' });
        Words.insert({ english: 'lean', korean: '기대다|기울어지다|성향|숙이다|살코기|' });
        Words.insert({ english: 'learn about', korean: '…에 대해 배우다. |' });
        Words.insert({ english: 'liberally', korean: '자유롭게|관대하게|아낌없이|' });
        Words.insert({ english: 'liberty', korean: '자유|리버티|해방|멋대로|' });
        Words.insert({ english: 'library', korean: '도서관|서재|장서|' });
        Words.insert({ english: 'license', korean: '면허|허가|자격증|라이센스|번호판|' });
        Words.insert({ english: 'lift', korean: '들어 올리다|해제하다|태워주다|엘리베이터|중량 운동|' });
        Words.insert({ english: 'light', korean: '밝게하다|조명|빛|가벼운|등|' });
        Words.insert({ english: 'lighting', korean: '조명|점화|점등|' });
        Words.insert({ english: 'lightly', korean: '가볍게|살짝|쉽게|들떠서|경솔히|' });
        Words.insert({ english: 'lightning', korean: '번개|벼락|전율|' });
        Words.insert({ english: 'load', korean: '싣다|짐|부담량|장전하다|부자인|' });
        Words.insert({ english: 'lobster', korean: '바닷가재|랍스터|얼굴이 붉은 사람|' });
        Words.insert({ english: 'locate', korean: '위치하다|찾아내다|자리잡고 있다|위치를 찾다|발견하다|' });
        Words.insert({ english: 'lock', korean: '잠그다|자물쇠|갇히다|닫다|고정시키다|' });
        Words.insert({ english: 'log', korean: '접속하다|통나무|기록하다|벌채하다|' });
        Words.insert({ english: 'make up on-e’s mind', korean: '결심하다, 결단을 내리다 |' });
        Words.insert({ english: 'marathon', korean: '마라톤|' });
        Words.insert({ english: 'married', korean: '결혼한|부부|기혼의|유부남|' });
        Words.insert({ english: 'mask', korean: '가면|마스크|감추다|안대|' });
        Words.insert({ english: 'mayfly', korean: '하루살이|제물낚시 바늘|' });
        Words.insert({ english: 'minute', korean: '분|잠깐|적은 양의|의사록|' });
        Words.insert({ english: 'misgiving', korean: '불안|의혹|' });
        Words.insert({ english: 'miss', korean: '그리워하다|놓치다|미스|실종되다|빼먹다|' });
        Words.insert({ english: 'modesty', korean: '겸손|정숙함|소박함|' });
        Words.insert({ english: 'moment', korean: '순간|지금|잠깐|때|기회|' });
        Words.insert({ english: 'month', korean: '달|개월|월|' });
        Words.insert({ english: 'mood', korean: '기분|분위기|무드|감정|마음|' });
        Words.insert({ english: 'mother', korean: '어머니|어미|수녀원장|모국의|' });
        Words.insert({ english: 'movie theater', korean: '영화관|' });
        Words.insert({ english: 'much', korean: '매우|많은|훨씬|크게|대부분|' });
        Words.insert({ english: 'much less', korean: '훨씬 더 적은|더군다나 …아니다|' });
        Words.insert({ english: 'mushroom', korean: '버섯|우후죽순격의|' });
        Words.insert({ english: 'musician', korean: '음악가|뮤지션|가수|' });
        Words.insert({ english: 'napkin', korean: '냅킨|' });
        Words.insert({ english: 'nation', korean: '국가|나라|국민|민족|' });
        Words.insert({ english: 'native', korean: '원주민의|태생의|토착의|토박이의|모국의|' });
        Words.insert({ english: 'near', korean: '근처|가깝게|인접한|거의|접근한|' });
        Words.insert({ english: 'nearby', korean: '근처의|인근의|가까운|주변의|이웃의|' });
        Words.insert({ english: 'nearly', korean: '거의|가까이|' });
        Words.insert({ english: 'necktie', korean: '넥타이|' });
        Words.insert({ english: 'need', korean: '필요|해야 한다|요구|수요|' });
        Words.insert({ english: 'needle', korean: '바늘|주사|침|' });
        Words.insert({ english: 'negotiation', korean: '협상|교섭|협의|거래|' });
        Words.insert({ english: 'never', korean: '결코|절대|전혀|설마|' });
        Words.insert({ english: 'new', korean: '새로운|새|최근의|신...|다시|' });
        Words.insert({ english: 'next', korean: '다음의|이후의|앞으로|차기|옆에|' });
        Words.insert({ english: 'next week', korean: '다음 주|' });
        Words.insert({ english: 'nuclear', korean: '핵의|원자력|원전|' });
        Words.insert({ english: 'number', korean: '수|다수|번호|…을 세다|' });
        Words.insert({ english: 'ocean', korean: '바다|해양|대양|' });
        Words.insert({ english: 'of course', korean: '물론|당연히|응|그렇지|사실|' });
        Words.insert({ english: 'officially', korean: '공식으로|본격적으로|공무상|' });
        Words.insert({ english: 'old', korean: '나이든|오래된|늙은|노인|낡은|' });
        Words.insert({ english: 'on foot', korean: '걸어서|도보로|착수되어|' });
        Words.insert({ english: 'on the internet', korean: '인터넷 상에서|' });
        Words.insert({ english: 'on the straight', korean: '똑바로|정직하게|일직선으로|' });
        Words.insert({ english: 'one', korean: '한번|하나|어느|유일한|한 개|' });
        Words.insert({ english: 'one day', korean: '어느 날|언젠가는|' });
        Words.insert({ english: 'onion', korean: '양파|' });
        Words.insert({ english: 'oops', korean: '이런|아차|아이코|' });
        Words.insert({ english: 'opportunity', korean: '기회|찬스|' });
        Words.insert({ english: 'or so', korean: '…쯤|…정도|…가량|' });
        Words.insert({ english: 'order', korean: '주문하다|명령하다|질서|순서|훈장|' });
        Words.insert({ english: 'originally', korean: '원래|본래|처음부터|처음에는|' });
        Words.insert({ english: 'other', korean: '다른|기타의|타인|나머지의|반면에|' });
        Words.insert({ english: 'pace', korean: '속도|페이스|보조를 맞추다|' });
        Words.insert({ english: 'painkiller', korean: '진통제|' });
        Words.insert({ english: 'pair', korean: '짝지어주다|한 쌍|2인조|한 벌|' });
        Words.insert({ english: 'pan', korean: '팬|냄비|프라이팬|' });
        Words.insert({ english: 'passport', korean: '여권|' });
        Words.insert({ english: 'past', korean: '과거의|과거형|지난|최근인|옛날의|' });
        Words.insert({ english: 'patent', korean: '특허|' });
        Words.insert({ english: 'pay', korean: '지불하다|임금|갚다|지급하다|보상하다|' });
        Words.insert({ english: 'peaceful', korean: '평화적인,평화로운,편안한|평화적인|평화로운|편안한|' });
        Words.insert({ english: 'pedestrian', korean: '보행의|도보의|평범한|' });
        Words.insert({ english: 'penalty', korean: '처벌|벌금|페널티|불이익|' });
        Words.insert({ english: 'pending', korean: '미정의|절박한|…중|' });
        Words.insert({ english: 'pension', korean: '연금|펜션|' });
        Words.insert({ english: 'people', korean: '사람들|국민|주민|인간|대중|' });
        Words.insert({ english: 'pepper', korean: '고추|후추|페퍼|피망|퍼붓다|' });
        Words.insert({ english: 'perfect', korean: '완벽한|최적의|완전한|퍼펙트|이상적인|' });
        Words.insert({ english: 'perfectionist', korean: '완전론의|완전주의자|완전론자|' });
        Words.insert({ english: 'perfectist', korean: '완벽주의자|' });
        Words.insert({ english: 'perform', korean: '공연하다|수행하다|연주하다|연기하다|노래하다|' });
        Words.insert({ english: 'periodical', korean: '정기 간행물|잡지|정기의|' });
        Words.insert({ english: 'permanent', korean: '영구적인|정규직의|상설의|영원한|파마|' });
        Words.insert({ english: 'permanently', korean: '영구적으로|영원히|상시|' });
        Words.insert({ english: 'permissible', korean: '허용되는|무방한|소지가 허가된|' });
        Words.insert({ english: 'permission', korean: '허가|허락|허용|승인|동의|' });
        Words.insert({ english: 'persuasion', korean: '설득|신앙|' });
        Words.insert({ english: 'plus', korean: '게다가|플러스|또한|더욱이|이상의|' });
        Words.insert({ english: 'point', korean: '점|지적하다|포인트|요점|점수|' });
        Words.insert({ english: 'police', korean: '경찰|치안|폴리스|공안|순경|' });
        Words.insert({ english: 'police station', korean: '경찰서|경찰 본서|' });
        Words.insert({ english: 'polite', korean: '예의 바른|공손한|정중한|' });
        Words.insert({ english: 'political', korean: '정치의|정계의|정당의|정략의|' });
        Words.insert({ english: 'poor', korean: '가난한|빈곤한|빈약한|부족한|나쁜|' });
        Words.insert({ english: 'professor', korean: '교수|박사|선생|' });
        Words.insert({ english: 'progress', korean: '진전|발전|진행|진척|진보|' });
        Words.insert({ english: 'prohibit', korean: '금지하다|막다|방해하다|통제하다|' });
        Words.insert({ english: 'rapid', korean: '빠른|급속한|급격한|신속한|가파른|' });
        Words.insert({ english: 'rate', korean: '요금|비율|속도|가격|평가되다|' });
        Words.insert({ english: 'rather', korean: '…보다는|오히려|차라리|…대신|다소|' });
        Words.insert({ english: 'rating', korean: '등급|평가|시청률|평점|' });
        Words.insert({ english: 'reach', korean: '도달하다|이르다|도착하다|닿다|이루다|' });
        Words.insert({ english: 'read a newspaper', korean: '신문을 읽다|' });
        Words.insert({ english: 'really', korean: '정말|아주|사실상|실제로|매우|' });
        Words.insert({ english: 'receive', korean: '받다|수상하다|얻다|당하다|접수하다|' });
        Words.insert({ english: 'recently', korean: '최근에|요즘에|얼마전|근래에|요즈음|' });
        Words.insert({ english: 'recognize', korean: '인정하다|인식하다|알아보다|알다|깨닫다|' });
        Words.insert({ english: 'recommend', korean: '추천하다|권하다|권고하다|제시하다|소개하다|' });
        Words.insert({ english: 'recruit', korean: '채용하다|모집하다|선발하다|신병|신입사원|' });
        Words.insert({ english: 'redeem', korean: '되찾다|상환하다|회복하다|' });
        Words.insert({ english: 'reef', korean: '산호초|암초|' });
        Words.insert({ english: 'refrain', korean: '자제하다|삼가다|후렴|' });
        Words.insert({ english: 'refresh', korean: '상쾌하게 하다| 되살리다|재충전하다|새롭게 하다|' });
        Words.insert({ english: 'refrigerator', korean: '냉장고|' });
        Words.insert({ english: 'refugee', korean: '난민|망명자|이탈자|' });
        Words.insert({ english: 'refuse', korean: '거부하다|거절하다|쓰레기|사절하다|' });
        Words.insert({ english: 'reporter', korean: '기자|리포터|' });
        Words.insert({ english: 'reserve', korean: '보유하다|예약하다|준비의|보호지역|매장량|' });
        Words.insert({ english: 'respective', korean: '각각의|각자의|…에 따라|저마다의|존경스러운|' });
        Words.insert({ english: 'respectively', korean: '각각|각자|각기|' });
        Words.insert({ english: 'responsible', korean: '책임이 있는|담당의|원인이 되는|역할을 하다|주범의|' });
        Words.insert({ english: 'restrain', korean: '제한하다|자제하다|금지하다|검거하다|압박하다|' });
        Words.insert({ english: 'restrict', korean: '제한하다|한정하다|금지하다|' });
        Words.insert({ english: 'result', korean: '결국|결과|성과|초래한다|결정|' });
        Words.insert({ english: 'resume', korean: '재개하다|이력서|다시 시작하다|되찾다|' });
        Words.insert({ english: 'retail', korean: '소매|유통|판매|매장|마트|' });
        Words.insert({ english: 'retire', korean: '은퇴하다|퇴직하다|퇴역시키다|퇴임하다|물러나다|' });
        Words.insert({ english: 'return', korean: '돌아오다|복귀하다|돌려주다|돌아가다|귀국|' });
        Words.insert({ english: 'rewarding', korean: '가치가 있는|보람이 있는|보람있는|' });
        Words.insert({ english: 'rice', korean: '쌀|밥|벼|' });
        Words.insert({ english: 'right', korean: '권리|인권|옳은|맞는|바로|' });
        Words.insert({ english: 'right now', korean: '지금|당장|현재|이제|요즘|' });
        Words.insert({ english: 'ring', korean: '반지|울리다|전화하다|링|고리|' });
        Words.insert({ english: 'riverside', korean: '강변|강기슭|리버사이드|' });
        Words.insert({ english: 'room', korean: '방|여지|공간|자리|장소|' });
        Words.insert({ english: 'rude', korean: '무례한|거친|' });
        Words.insert({ english: 'safe', korean: '안전한|무사한|금고|세이프의|신중한|' });
        Words.insert({ english: 'safety', korean: '안전|' });
        Words.insert({ english: 'salary', korean: '월급|급여|연봉|임금|…료|' });
        Words.insert({ english: 'sale', korean: '판매|매각|세일|매매|매출|' });
        Words.insert({ english: 'same', korean: '같은|동일한|똑같은|마찬가지로|일치하는|' });
        Words.insert({ english: 'satisfying', korean: '만족시키는|충분한|납득이 가는|' });
        Words.insert({ english: 'savor', korean: '맛|풍미|맛이 나다|' });
        Words.insert({ english: 'scale', korean: '규모|등급|비늘|척도|저울|' });
        Words.insert({ english: 'scholarship', korean: '장학|장학금|학문|' });
        Words.insert({ english: 'science', korean: '과학|사이언스|학문|' });
        Words.insert({ english: 'seabed', korean: '해저|' });
        Words.insert({ english: 'seat', korean: '자리잡다|자리|좌석|앉다|의석|' });
        Words.insert({ english: 'secretary', korean: '장관|비서|차관|사무총장|간사|' });
        Words.insert({ english: 'see', korean: '보다|알다|만나다|지켜보다|확인하다|' });
        Words.insert({ english: 'seem like', korean: '…처럼 보이다.|' });
        Words.insert({ english: 'seem to', korean: '…할 모양이다|' });
        Words.insert({ english: 'sell', korean: '팔다|판매하다|매각하다|매도하다|매출|' });
        Words.insert({ english: 'send out', korean: '배포하다|내다|가져 오도록 주문하다|' });
        Words.insert({ english: 'serious', korean: '심각한|진지한|정말|중대한|위험한|' });
        Words.insert({ english: 'servant', korean: '공무원|하인|고용인|봉사자|' });
        Words.insert({ english: 'server', korean: '근무자|서버|시중 드는 사람|' });
        Words.insert({ english: 'several', korean: '몇|여러 가지의|몇 가지의|수 많은|몇 개의|' });
        Words.insert({ english: 'severe', korean: '심각한|가차없는|엄격한|' });
        Words.insert({ english: 'shake hands', korean: '악수, 악수하다[with ‥]|' });
        Words.insert({ english: 'shall', korean: '…해주어야겠다|…할까요|…일 것이다|…해야 하다|…시키겠다|' });
        Words.insert({ english: 'share', korean: '공유하다|나누다|점유하다|주식|주가|' });
        Words.insert({ english: 'shatter', korean: '산산이 부서지다|파괴|분쇄하다|풍비박산|' });
        Words.insert({ english: 'she', korean: '그녀|그 여자|' });
        Words.insert({ english: 'shellfish', korean: '조개|갑각강의 동물|거북복|' });
        Words.insert({ english: 'shepherd', korean: '셰퍼드|양치기|목자|' });
        Words.insert({ english: 'shipwreck', korean: '난파하다|난파|난파선|' });
        Words.insert({ english: 'shipyard', korean: '조선소|' });
        Words.insert({ english: 'similar', korean: '비슷한|유사한|같은|흡사한|닮은|' });
        Words.insert({ english: 'simply', korean: '단순히|그저|간단히|아주|전혀|' });
        Words.insert({ english: 'since', korean: '…이후|…때부터|…이래|그 후|' });
        Words.insert({ english: 'single', korean: '하나의|싱글|단일의|독신의|유일한|' });
        Words.insert({ english: 'singly', korean: '단독으로|하나씩|홀로|' });
        Words.insert({ english: 'sister', korean: '여동생|자매|언니|누나|수녀|' });
        Words.insert({ english: 'site', korean: '사이트|현장|유적지|장소|부지|' });
        Words.insert({ english: 'situation', korean: '상황|사태|상태|입장|경우|' });
        Words.insert({ english: 'skill', korean: '기술|실력|솜씨|기능|' });
        Words.insert({ english: 'solution', korean: '해결책|방안|해법|솔루션|용액|' });
        Words.insert({ english: 'solve', korean: '해결하다|풀다|' });
        Words.insert({ english: 'some', korean: '일부|몇|어떤|…중에는|약간|' });
        Words.insert({ english: 'someday', korean: '언젠가|머지않아|훗날|' });
        Words.insert({ english: 'someone', korean: '누군가|어떤 사람|' });
        Words.insert({ english: 'something', korean: '무언가|어떤 것|어떤 일|중요한 것|조금|' });
        Words.insert({ english: 'son', korean: '아들|자식|자손|양자|' });
        Words.insert({ english: 'soon', korean: '곧|빨리|조만간|…대로|바로|' });
        Words.insert({ english: 'spade', korean: '스페이드|삽|' });
        Words.insert({ english: 'special', korean: '특별한|특수한|스페셜|임시의|특이한|' });
        Words.insert({ english: 'spell', korean: '철자하다|마법|의미하다|기간|초래하다|' });
        Words.insert({ english: 'spider', korean: '거미|' });
        Words.insert({ english: 'spinach', korean: '시금치|그 잎|돈|' });
        Words.insert({ english: 'spirit', korean: '정신|사람|유령|영혼|마음|' });
        Words.insert({ english: 'spot', korean: '장소|위|발견하다|점|관광지|' });
        Words.insert({ english: 'spring break', korean: '봄방학|' });
        Words.insert({ english: 'stamp', korean: '우표|도장|찍다|인지|짓밟다|' });
        Words.insert({ english: 'stand for', korean: '…을 나타내다|상징하다|대표하다|' });
        Words.insert({ english: 'start', korean: '시작하다|출발점|출발하다|처음|선발|' });
        Words.insert({ english: 'station', korean: '역|정거장|방송국|주둔하다|기지|' });
        Words.insert({ english: 'stay', korean: '머무르다|지내다|유지하다|체류하다|보내다|' });
        Words.insert({ english: 'straight', korean: '연속한|똑바로|곧장|바로|직선|' });
        Words.insert({ english: 'strategy', korean: '전략|계획|방법|' });
        Words.insert({ english: 'stress', korean: '스트레스|강조하다|압박|중점을 두다|' });
        Words.insert({ english: 'study', korean: '연구|공부|조사|학업|전공하다|' });
        Words.insert({ english: 'style', korean: '스타일|방식|형식|모양|양식|' });
        Words.insert({ english: 'stylish', korean: '유행의|멋진|유행에 맞는|' });
        Words.insert({ english: 'submarine', korean: '잠수함|' });
        Words.insert({ english: 'success', korean: '성공|성과|성공한 사람|달성|대히트|' });
        Words.insert({ english: 'such', korean: '…같은|그러한|이러한|그렇게|매우|' });
        Words.insert({ english: 'such as', korean: '같은|등|이러한|예를 들면|특히|' });
        Words.insert({ english: 'sucking', korean: '빠는|젖내나는|아직 젖이 떨어지지 않은|' });
        Words.insert({ english: 'suddenly', korean: '갑자기|순식간에|' });
        Words.insert({ english: 'suggest', korean: '제안하다|시사하다|제시하다|암시하다|제의하다|' });
        Words.insert({ english: 'suit', korean: '정장|어울리다|옷|소송|' });
        Words.insert({ english: 'suitable', korean: '적합한|적당한|알맞은|적절한|' });
        Words.insert({ english: 'summary', korean: '요약|개괄|약식|성명|' });
        Words.insert({ english: 'sun', korean: '태양|해|햇볕|' });
        Words.insert({ english: 'supper', korean: '저녁 식사|만찬|야식|' });
        Words.insert({ english: 'sure', korean: '확신하고|확실히|분명히|물론|꼭|' });
        Words.insert({ english: 'sweep', korean: '휩쓸다|청소하다|압승하다|조사하다|' });
        Words.insert({ english: 'temporary', korean: '임시의|일시적인|임시 고용|' });
        Words.insert({ english: 'tempt', korean: '하고 싶은|유혹하다|끌다|꾀다|' });
        Words.insert({ english: 'tension', korean: '긴장|갈등|불안|팽팽함|' });
        Words.insert({ english: 'than', korean: '보다|다름아닌|보다는|…이외의|' });
        Words.insert({ english: 'thanks for', korean: '~에 대해 감사하다. 고마워하다.|' });
        Words.insert({ english: 'that', korean: '저것|것|그|다른|' });
        Words.insert({ english: 'thing', korean: '것|일|상황|물건|짓|' });
        Words.insert({ english: 'think', korean: '생각하다|같다|평가하다|상상하다|예상하다|' });
        Words.insert({ english: 'think the same way', korean: '같은 생각이다|' });
        Words.insert({ english: 'thread', korean: '실|공통된 주제|가는 선|옷|' });
        Words.insert({ english: 'through', korean: '통하여|지나서|…때문에|헤쳐나가다|…사이를|' });
        Words.insert({ english: 'ticket', korean: '승차권|티켓|표|입장권|딱지|' });
        Words.insert({ english: 'timeless', korean: '시간을 초월한|시대를 초월한|영원한|' });
        Words.insert({ english: 'today', korean: '오늘날|오늘|현재|지금|요즘|' });
        Words.insert({ english: 'too', korean: '너무|또한|지나치게|매우|' });
        Words.insert({ english: 'toothache', korean: '치통|' });
        Words.insert({ english: 'totally', korean: '완전히|전혀|정말|전적으로|전부|' });
        Words.insert({ english: 'touching', korean: '…에 관하여|감동적인|남의 마음을 움직이는|' });
        Words.insert({ english: 'tough', korean: '힘든|어려운|강한|거친|터프한|' });
        Words.insert({ english: 'tourist', korean: '관광객|관광의|' });
        Words.insert({ english: 'tradition', korean: '전통|전해지는|관습|' });
        Words.insert({ english: 'traditional', korean: '전통적인|구식의|고풍의|' });
        Words.insert({ english: 'tree', korean: '나무|트리|가계도|수목|관계|' });
        Words.insert({ english: 'trick', korean: '속이다|묘기|재주|장난|요령|' });
        Words.insert({ english: 'tried', korean: '노력한|…하려고 한|먹어 본|입어 본|' });
        Words.insert({ english: 'trust', korean: '신뢰|믿음|기업합동|신탁|맡기다|' });
        Words.insert({ english: 'truth', korean: '진실|사실|진상|진리|진심|' });
        Words.insert({ english: 'try on', korean: '입어 보다|시험 착용|신어보다|' });
        Words.insert({ english: 'tuck in', korean: '진수 성찬|걸어지르는 부분|' });
        Words.insert({ english: 'tug of war', korean: '줄다리기|세력 싸움|쟁탈전|' });
        Words.insert({ english: 'tune', korean: '곡|주파수를 맞추다|조율하다|연주하다|서로 맞다|' });
        Words.insert({ english: 'turkey', korean: '터키|칠면조|' });
        Words.insert({ english: 'turn', korean: '되다|돌리다|바꾸다|켜다|전환하다|' });
        Words.insert({ english: 'turnip', korean: '순무|무|유행에 뒤떨어진 대형 회중 시계|' });
        Words.insert({ english: 'turtle', korean: '거북|자라|' });
        Words.insert({ english: 'two', korean: '둘|' });
        Words.insert({ english: 'type', korean: '종류|유형|타자|양식|타입|' });
        Words.insert({ english: 'typhoon', korean: '태풍|폭풍|제2차 세계 대전 당시 영국 폭격기 이름|' });
        Words.insert({ english: 'uncomfortable', korean: '불편한|불쾌감을 주는|민감한|' });
        Words.insert({ english: 'unconscious', korean: '무의식의|의식을 잃은|' });
        Words.insert({ english: 'uncool', korean: '싫은|성가신|거친|' });
        Words.insert({ english: 'undergo', korean: '받다|겪다|진행하다|…을 견디다|' });
        Words.insert({ english: 'undertaking', korean: '사업|맡은|실시|' });
        Words.insert({ english: 'unemployment', korean: '실업|' });
        Words.insert({ english: 'unexpected', korean: '예기치 않은|' });
        Words.insert({ english: 'unfair', korean: '불공평한|불공정한|부당한|억울한|' });
        Words.insert({ english: 'uniform', korean: '유니폼|똑같은|일제히|' });
        Words.insert({ english: 'universe', korean: '우주|세계|' });
        Words.insert({ english: 'unjust', korean: '부당한|' });
        Words.insert({ english: 'unknown', korean: '알려지지 않은|알 수 없는|미지의|미상의|무명의|' });
        Words.insert({ english: 'unlawful', korean: '법에 어긋나는|적출이 아닌|불법적인|' });
        Words.insert({ english: 'unlock', korean: '열다|잠기지 않은|밝히다|' });
        Words.insert({ english: 'unnatural', korean: '부자연스러운|비정상적인|극도로 잔혹한|' });
        Words.insert({ english: 'unplug', korean: '마개를 뽑다|…에서 전원을 끊다|장애물을 제거하다|' });
        Words.insert({ english: 'unsatisfactory', korean: '불만족스러운|불충분한|' });
        Words.insert({ english: 'unselfish', korean: '이타적인|무사한|이기적이 아닌|' });
        Words.insert({ english: 'until', korean: '…할 때까지|…까지|…이 되어 비로소|' });
        Words.insert({ english: 'upset', korean: '화난|기분 나쁜|당황|혼란|아픈|' });
        Words.insert({ english: 'usage', korean: '사용|용법|소비|용도|' });
        Words.insert({ english: 'useful', korean: '유용한|쓸모 있는|도움이 되는|유익한|실용적인|' });
        Words.insert({ english: 'usually', korean: '보통|대개|일반적으로|늘|평소|' });
        Words.insert({ english: 'vacancy', korean: '빈자리|빈방|결원|' });
        Words.insert({ english: 'valley', korean: '계곡|유역|골짜기|' });
        Words.insert({ english: 'various', korean: '다양한|여러가지의|많은|얼룩덜룩한|' });
        Words.insert({ english: 'vase', korean: '꽃병|항아리|' });
        Words.insert({ english: 'vegetable', korean: '야채|식물|' });
        Words.insert({ english: 'vocalist', korean: 'a person who sings|' });
        Words.insert({ english: 'volleyball', korean: '배구|' });
        Words.insert({ english: 'wait', korean: '기다리다|지켜 보다|대기하다|기대하다|' });
        Words.insert({ english: 'waitress', korean: '웨이트리스|여종업원|' });
        Words.insert({ english: 'walk on', korean: '단역|단역 배우|단역의|' });
        Words.insert({ english: 'warship', korean: '군함|전함|' });
        Words.insert({ english: 'watch', korean: '보다|지켜보다|관람하다|시계|감시하다|' });
        Words.insert({ english: 'watermelon', korean: '수박|그 과일|' });
        Words.insert({ english: 'wear', korean: '입다|쓰다|옷|착용하다|끼다|' });
        Words.insert({ english: 'wedding preparation', korean: '결혼 준비|' });
        Words.insert({ english: 'welcome', korean: '환영하다|맞이하다|환대하다|' });
        Words.insert({ english: 'well', korean: '잘|흠|충분히|나은|우물|' });
        Words.insert({ english: 'whale', korean: '고래|즐거운|열심인|' });
        Words.insert({ english: 'what', korean: '무엇|어떻게|뭐라고|무슨|어떤|' });
        Words.insert({ english: 'where', korean: '어디|곳|장소|' });
        Words.insert({ english: 'which', korean: '어떤|어느|' });
        Words.insert({ english: 'who', korean: '누구|' });
        Words.insert({ english: 'wish', korean: '바라다|…좋겠어|…싶다|소원|기원하다|' });
        Words.insert({ english: 'without', korean: '…없이|…하지 않고|' });
        Words.insert({ english: 'wonderful', korean: '멋진|훌륭한|좋은|놀라운|행복한|' });
        Words.insert({ english: 'working conditions', korean: '노동[근무] 조건. |' });
        Words.insert({ english: 'worry', korean: '걱정하다|우려하다|염려|불안|근심하다|' });
        Words.insert({ english: 'younger', korean: '더 젊은|더 어린|동생인|젊은이|아래의|' });
        Words.insert({ english: 'your', korean: '당신의|너의|여러분의|자네의|' });
	}
});
